/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThankYouPhoneRouteImport } from './routes/thank-you.$phone'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouPhoneRoute = ThankYouPhoneRouteImport.update({
  id: '/$phone',
  path: '/$phone',
  getParentRoute: () => ThankYouRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRouteWithChildren
  '/thank-you/$phone': typeof ThankYouPhoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRouteWithChildren
  '/thank-you/$phone': typeof ThankYouPhoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRouteWithChildren
  '/thank-you/$phone': typeof ThankYouPhoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thank-you' | '/thank-you/$phone'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thank-you' | '/thank-you/$phone'
  id: '__root__' | '/' | '/thank-you' | '/thank-you/$phone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThankYouRoute: typeof ThankYouRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you/$phone': {
      id: '/thank-you/$phone'
      path: '/$phone'
      fullPath: '/thank-you/$phone'
      preLoaderRoute: typeof ThankYouPhoneRouteImport
      parentRoute: typeof ThankYouRoute
    }
  }
}

interface ThankYouRouteChildren {
  ThankYouPhoneRoute: typeof ThankYouPhoneRoute
}

const ThankYouRouteChildren: ThankYouRouteChildren = {
  ThankYouPhoneRoute: ThankYouPhoneRoute,
}

const ThankYouRouteWithChildren = ThankYouRoute._addFileChildren(
  ThankYouRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThankYouRoute: ThankYouRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
